### ISSUE TITLE
Song Unavailable

### ISSUE THREAD

**Issue by ghost** [lolPants/beatsaver-reloaded#109] opened 2020-12-31 18:23 UTC
## Platform
**This bug report concerns:** *(select all that apply)*
- [x] Client
- [x] Server

## Details
**Please describe the problem you are having in as much detail as possible:**
unable to find songs
## Reproducing the Problem
**Please include detailed steps to reproduce the problem:**
enter the site and search with any amount of letters
Please recognise i have deleted the tab and refreshed 
![image](https://user-images.githubusercontent.com/74470480/103421607-30733900-4b95-11eb-8d6e-452f9d32cac7.png)

**Comment by luludotdev** [comment] 2020-12-31 18:26
Dupe of #107

**Closed as completed by luludotdev** 2020-12-31 18:26 UTC

**Comment by ghost** [comment] 2020-12-31 18:33
ah didnt notice it sorry
