### ISSUE TITLE
Website Down?

### ISSUE THREAD

**Issue by get1748982** [lolPants/beatsaver-reloaded#110] opened 2021-01-01 02:01 UTC
The website has seem to be down for the last 2 days or so, does anyone know when it will be back up?

**Comment by RyVador** [comment] 2021-01-01 03:06
this has been happening to me to, looks like searching, let along downloading songs, doesn't work. Same with registering accounts

**Comment by luludotdev** [comment] 2021-01-01 03:26
Dupe of #107

**Closed as completed by luludotdev** 2021-01-01 03:26 UTC
